import { z } from "zod";

const presetSchema = z.object({
  id: z.string().regex(/^[a-z0-9-]+$/),
  version: z.number().int().positive(),
  name: z.string().min(1),
  description: z.string().min(1),
  accent: z.string().regex(/^#[0-9a-fA-F]{6}$/),
  hue: z.number().min(0).max(360),
  prompt: z.string().min(24),
  referenceImage: z.enum(["disc-2"]).optional(),
});

export type Preset = z.infer<typeof presetSchema>;

const preservationPrompt =
  "Preserve the main subject, recognizable identity, pose, composition, camera angle, and important scene geometry. Apply the requested aesthetic consistently across the image. Do not add captions, logos, borders, signatures, or watermarks.";

const fantasyPreservationPrompt =
  "Preserve each person's recognizable facial identity, age, expression, and pose. Replace contemporary clothing and accessories with the requested fantasy designs. Replace modern headwear with a handcrafted period-style cloth cap or hood that keeps the face visible. Adapt hairstyles to the setting while retaining each person's facial identity. Preserve the composition, camera angle, and overall layout while reinterpreting surroundings as fantasy equivalents. Keep people comfortably clothed and the scene peaceful. Use original costumes, architecture, and heraldry. Do not add captions, logos, borders, signatures, or watermarks.";

const presetCatalog: Preset[] = z.array(presetSchema).parse([
  {
    id: "post-apocalypse",
    version: 3,
    name: "After the End",
    description: "A quiet world reclaimed by nature: weathered buildings, greenery, and amber light.",
    accent: "#ff6c51",
    hue: 18,
    prompt: `Restyle the supplied photograph as a peaceful, long-abandoned retro-future world reclaimed by nature. Age the existing buildings, furniture, and objects with faded paint, worn surfaces, a little dust, and creeping greenery. Use warm amber sunlight, muted earth tones, and cinematic film texture. Keep the scene calm and habitable. Keep any people and animals healthy and relaxed, with their appearance and clothing intact. ${preservationPrompt}`,
  },
  {
    id: "kid-drawing",
    version: 1,
    name: "Fridge Masterpiece",
    description: "Wobbly crayons, joyful colors, and the confidence of a five-year-old artist.",
    accent: "#ffd84a",
    hue: 52,
    prompt: `Redraw the supplied photograph as an exuberant young child's crayon drawing on lightly lined off-white paper. Use wobbly outlines, uneven coloring, simplified shapes, cheerful colors, and charmingly imperfect proportions. ${preservationPrompt}`,
  },
  {
    id: "alien-visitor",
    version: 2,
    name: "First Contact",
    description: "A friendly visitor, green-violet light, and a little everyday science-fiction wonder.",
    accent: "#d7ff42",
    hue: 112,
    prompt: `Restyle the supplied photograph as a warm, playful science-fiction movie scene about meeting a friendly visitor from another planet. Add one small, friendly robot-like alien companion in an open area of the background, soft green-violet accent lighting, and a few practical retro-futuristic details. Keep the existing people and animals unchanged, healthy, relaxed, and clearly separate from the new companion; keep their clothing intact. The mood is welcoming and curious. ${preservationPrompt}`,
  },
  {
    id: "claymation",
    version: 1,
    name: "Tiny Clay World",
    description: "Hand-shaped characters, miniature sets, fingerprints, and stop-motion charm.",
    accent: "#f39b69",
    hue: 28,
    prompt: `Rebuild the supplied photograph as a handcrafted stop-motion clay animation frame. Everything should look sculpted from colorful modeling clay with tiny fingerprints, miniature practical sets, soft studio lighting, and shallow depth of field. ${preservationPrompt}`,
  },
  {
    id: "disposable-90s",
    version: 1,
    name: "Found in 1997",
    description: "Direct flash, soft focus, chunky grain, and a slightly questionable timestamp.",
    accent: "#5ac6c8",
    hue: 184,
    prompt: `Make the supplied photograph look like an authentic late-1990s consumer disposable-camera print. Use direct on-camera flash, slightly missed focus, visible film grain, modest color casts, imperfect exposure, and candid snapshot energy. Do not add a border or timestamp. ${preservationPrompt}`,
  },
  {
    id: "storybook",
    version: 1,
    name: "Bedtime Legend",
    description: "A warm, richly painted page from an old and well-loved storybook.",
    accent: "#6657de",
    hue: 248,
    prompt: `Illustrate the supplied photograph as a richly painted page from a timeless children's storybook. Use expressive gouache and watercolor textures, warm pools of light, gentle whimsy, detailed natural forms, and a sense of quiet adventure. ${preservationPrompt}`,
  },
  {
    id: "panel-one",
    version: 1,
    name: "Panel One",
    description: "Bold comic inks, halftone dots, and vintage printed color.",
    accent: "#ec765e",
    hue: 10,
    prompt: `Redraw the entire supplied photograph as a single full-bleed vintage color comic illustration. Use confident black brush outlines, expressive inked faces, simplified shadow shapes, saturated flat print colors, subtle Ben-Day halftone dots, and slightly imperfect ink registration on paper. Render all people, animals, objects, and surroundings in the same illustrated style. Keep the photographed everyday activity and give the scene lively visual energy. Use original character designs. ${preservationPrompt}`,
  },
  {
    id: "after-school",
    version: 1,
    name: "Anime Cel",
    description: "A nostalgic cel-anime frame with painted backgrounds and expressive faces.",
    accent: "#f89db7",
    hue: 342,
    prompt: `Redraw the entire supplied photograph as a nostalgic late-1990s hand-drawn cel-anime frame. Use fine confident linework, expressive eyes and brows, angular locks of hair, two-tone cel shadows, restrained highlights, richly hand-painted backgrounds, and a delicate trace of analog film grain. Translate the subjects into original anime character designs while retaining their distinctive facial features, age, expression, hairstyle, and clothing. Keep the atmosphere natural and grounded in the photographed moment. ${preservationPrompt}`,
  },
  {
    id: "prime-time",
    version: 1,
    name: "Prime Time",
    description: "Your everyday cast in a bright, flat-color animated sitcom.",
    accent: "#f2c94c",
    hue: 46,
    prompt: `Redraw the entire supplied photograph as a deliberately simple two-dimensional animated television sitcom cel. Use bold even dark outlines, large flat untextured color fills, small black-dot pupils in simple rounded eyes, chunky rounded noses, economical mouth lines, slightly ungainly comic proportions, and very minimal shadow shapes. Simplify faces into an original, gently satirical cartoon design that retains each photographed person's distinctive face shape, age, hair, and clothes. Keep all subjects and background objects equally graphic and flat, with a bright warm palette and ordinary everyday atmosphere. Use original character designs. ${preservationPrompt}`,
  },
  {
    id: "once-upon-a-cel",
    version: 1,
    name: "Once Upon a Cel",
    description: "Expressive hand-drawn characters against lush animated-film scenery.",
    accent: "#bd9be8",
    hue: 268,
    prompt: `Redraw the supplied photograph as a frame from an original hand-drawn animated fairy-tale feature film. Draw the subjects with graceful flowing contours, appealing rounded forms, expressive faces, carefully painted cel colors, and fluid-looking poses that match the photograph. Paint the surroundings with layered gouache detail, atmospheric depth, warm theatrical lighting, and a quiet sense of wonder. Use crisp character cels against richly painted scenery. Keep the original subjects recognizable and create original character designs. ${preservationPrompt}`,
  },
  {
    id: "big-screen",
    version: 1,
    name: "3D Toon",
    description: "Expressive sculpted characters and warm cinematic 3D animation.",
    accent: "#f7a85c",
    hue: 30,
    prompt: `Rebuild the entire supplied photograph as a polished frame from an original three-dimensional animated family feature. Translate people and animals into expressive sculpted characters with gently exaggerated eyes and brows, rounded but distinctive facial shapes, carefully groomed hair or fur, and tactile clothing. Give the whole scene dimensional modeled geometry, soft material shading, warm cinematic lighting, subtle depth of field, and rich color. Retain each subject's recognizable identity, age, expression, and characteristic details through the stylization. Use original character designs. ${preservationPrompt}`,
  },
  {
    id: "pocket-arcade",
    version: 1,
    name: "Title Screen",
    description: "Detailed pixel illustration with the atmosphere of a retro title screen.",
    accent: "#75bdff",
    hue: 208,
    prompt: `Rebuild the entire supplied photograph as detailed 16-bit pixel art, as though drawn on a roughly 320-pixel-wide game canvas and enlarged with crisp nearest-neighbor pixels. Construct every subject and background object from deliberate square pixel clusters with a limited coordinated palette, stepped contours, simple sprite-like shading, and selective dithering. Preserve recognizable facial, hair, and clothing cues using carefully placed pixels. Apply the pixel-art construction throughout the scene. ${preservationPrompt}`,
  },
  {
    id: "player-one",
    version: 1,
    name: "Player One",
    description: "Small playable sprites in a full 16-bit game scene built from your photo.",
    accent: "#8ac975",
    hue: 106,
    prompt: `Rebuild the photographed scene as an actual playable 16-bit pixel-art game screen. Translate each person or animal into a small full-body gameplay sprite, approximately 32-to-48 source pixels tall, within a roughly 256-by-224-pixel game scene enlarged with crisp nearest-neighbor pixels. Each character should occupy at most one third of the screen height, surrounded by a readable tile-based environment made from recognizable objects in the photograph. For a close-up portrait, pull the game camera back and reinterpret the person as a complete small sprite wearing a coherent outfit based on their visible clothing. Preserve distinctive hair, headwear, clothing colors, and recognizable character cues using very few pixels. Use simple sprite proportions, clear outlined silhouettes, economical three-tone shading, repeating environment tiles, and a limited coordinated palette. Adapt the pose and location into a coherent side-view or three-quarter-view game scene. Show the characters within their game environment rather than as large portrait artwork. Do not add a title, text, speech bubbles, HUD, menus, borders, logos, signatures, or watermarks.`,
  },
  {
    id: "memory-card",
    version: 3,
    name: "Insert Disc 2",
    description: "Chunky console characters, soft photographic textures, and a wider view of close-up portraits.",
    accent: "#a6b987",
    hue: 82,
    prompt: "Rebuild the photographed subjects and setting as an in-engine screenshot from a late-1990s 3D console adventure game. Use very simple chunky character meshes: broad torso slabs, thick box-shaped upper arms and forearms, angular elbows, blocky hands, and solid geometric hair. The coarse model should be most apparent in its outline and joints. Shade continuously across the mesh with smooth vertex shading so individual triangles do not become patches of different color. Map soft low-resolution photographic texture art onto these simple forms. Put recognizable facial features, skin shadows, eyebrows, lips, and facial hair into one blurry painted face texture; give the face a few broad contours and a simple nose. Paint clothing folds, seams, pockets, and material detail into small diffuse texture maps. Keep natural-looking blended color within these textures rather than a grid of colored blocks or a mosaic of triangles. Give the surroundings textured coarse geometry and baked lighting, with richly painted architectural surfaces where appropriate. Present the whole scene as a gently enlarged roughly 320-by-240-pixel game frame, with soft jagged edges, slightly muddy textures, muted colors, and simple lighting. Preserve the subjects' recognizable appearance, age, main clothing colors, and activity. Retain only the people and animals present in the photograph, including keeping empty spaces unoccupied. Do not add text, captions, game interfaces, borders, logos, or watermarks. For a close-up portrait, move the virtual game camera back to show the same person from the waist up with their shoulders, upper arms, and hands visible, so their chunky character model reads clearly. Infer a simple pose and the unseen parts of their outfit from the photograph. For an already wider photo, keep its framing and layout. Reuse the recognizable setting rather than replacing it with an unrelated game location.",
  },
  {
    id: "disc-2-smooth",
    version: 1,
    name: "Disc 2 · Smooth",
    description: "Test: smooth shading and soft photographic textures; keeps the original framing.",
    accent: "#8ebf96",
    hue: 130,
    prompt: "Rebuild the photographed subjects and setting as an in-engine screenshot from a late-1990s 3D console adventure game. Use very simple chunky character meshes: broad torso slabs, thick box-shaped upper arms and forearms, angular elbows, blocky hands, and solid geometric hair. The coarse model should be most apparent in its outline and joints. Shade continuously across the mesh with smooth vertex shading so individual triangles do not become patches of different color. Map soft low-resolution photographic texture art onto these simple forms. Put recognizable facial features, skin shadows, eyebrows, lips, and facial hair into one blurry painted face texture; give the face a few broad contours and a simple nose. Paint clothing folds, seams, pockets, and material detail into small diffuse texture maps. Keep natural-looking blended color within these textures rather than a grid of colored blocks or a mosaic of triangles. Give the surroundings textured coarse geometry and baked lighting, with richly painted architectural surfaces where appropriate. Present the whole scene as a gently enlarged roughly 320-by-240-pixel game frame, with soft jagged edges, slightly muddy textures, muted colors, and simple lighting. Preserve the subjects' recognizable appearance, age, main clothing colors, and activity. Retain only the people and animals present in the photograph, including keeping empty spaces unoccupied. Do not add text, captions, game interfaces, borders, logos, or watermarks. Preserve the original framing, viewpoint, and scene layout.",
  },
  {
    id: "disc-2-wide",
    version: 1,
    name: "Disc 2 · Wide",
    description: "Test: the current Disc 2 look with close-up portraits pulled back to the waist.",
    accent: "#8ebf96",
    hue: 130,
    prompt: "Reconstruct only the subjects and setting present in the supplied photograph as a textured late-1990s console adventure-game cutscene. If people are present, build them from chunky low-polygon meshes with broad squared shoulders, thick prismatic arms, angular elbows, blocky hands, and simple solid hair shapes. Wrap every mesh in visibly low-resolution photographic bitmap textures: paint recognizable eyes, brows, lips, stubble, skin shading, hair strands, clothing folds, stitching, and fabric patterns into the texture maps. Facial detail should come primarily from a blurry painted face texture on a simple head mesh. Use roughly 64-to-128-pixel face textures and small clothing texture atlases with stretched texels and visible seams. Keep the coarse geometry clear at silhouettes and joints while smoothly shading across the large mesh faces. Render background surfaces with similarly low-resolution photographic materials and baked architectural detail. Aim for the imperfect realism of an old textured game cutscene, with muted colors, baked shadows, soft vertex lighting, and slightly jagged raster edges. Preserve the photographed subjects' recognizable appearance, clothing colors, activity and recognizable scene layout. Keep unoccupied spaces unoccupied; do not invent additional people or animals. Do not add captions, logos, borders, signatures, or watermarks. For a close-up portrait, move the virtual game camera back to show the same person from the waist up with their shoulders, upper arms, and hands visible. Infer a simple pose and the unseen parts of their outfit from the photograph. For an already wider photo, keep its framing and layout.",
  },
  {
    id: "disc-2-smooth-wide",
    version: 1,
    name: "Disc 2 · Smooth+Wide",
    description: "Test: smooth shading plus a wider view of close-up portraits.",
    accent: "#8ebf96",
    hue: 130,
    prompt: "Rebuild the photographed subjects and setting as an in-engine screenshot from a late-1990s 3D console adventure game. Use very simple chunky character meshes: broad torso slabs, thick box-shaped upper arms and forearms, angular elbows, blocky hands, and solid geometric hair. The coarse model should be most apparent in its outline and joints. Shade continuously across the mesh with smooth vertex shading so individual triangles do not become patches of different color. Map soft low-resolution photographic texture art onto these simple forms. Put recognizable facial features, skin shadows, eyebrows, lips, and facial hair into one blurry painted face texture; give the face a few broad contours and a simple nose. Paint clothing folds, seams, pockets, and material detail into small diffuse texture maps. Keep natural-looking blended color within these textures rather than a grid of colored blocks or a mosaic of triangles. Give the surroundings textured coarse geometry and baked lighting, with richly painted architectural surfaces where appropriate. Present the whole scene as a gently enlarged roughly 320-by-240-pixel game frame, with soft jagged edges, slightly muddy textures, muted colors, and simple lighting. Preserve the subjects' recognizable appearance, age, main clothing colors, and activity. Retain only the people and animals present in the photograph, including keeping empty spaces unoccupied. Do not add text, captions, game interfaces, borders, logos, or watermarks. For a close-up portrait, move the virtual game camera back to show the same person from the waist up with their shoulders, upper arms, and hands visible, so their chunky character model reads clearly. Infer a simple pose and the unseen parts of their outfit from the photograph. For an already wider photo, keep its framing and layout. Reuse the recognizable setting rather than replacing it with an unrelated game location.",
  },
  {
    id: "disc-2-1996",
    version: 1,
    name: "Disc 2 · 1996",
    description: "Test: the textured characters and painted scenery of a 1996 console adventure.",
    accent: "#8ebf96",
    hue: 130,
    prompt: "Reimagine this photograph using the character-rendering look of the original 1996 Resident Evil game on PlayStation. Depict only the same peaceful everyday subjects and activity shown in the photo. Use original character appearances based on the photographed people, with their own faces, ages, clothing colors, and poses. Reconstruct bodies as extremely simple segmented meshes: box-shaped torsos, broad prism-shaped upper arms and forearms, obvious angular elbows, solid mitten hands, and chunky hair silhouettes. Faces and clothing must use blurry, low-resolution photographic bitmap textures stretched over simple geometry. Use realistic human proportions and small natural eyes, with facial detail painted into the face texture. Render the photographed surroundings as a detailed but low-resolution pre-rendered background in the same period game style. The result should look like an actual old game screenshot with awkward textured realism, simple lighting, and rough raster edges. Preserve the original cast of people and animals and the scene composition. Do not introduce game characters, weapons, injuries, text, interfaces, borders, logos, or watermarks.",
  },
  {
    id: "disc-2-reference",
    version: 1,
    name: "Disc 2 · Reference",
    description: "Test: uses the supplied game screenshot to guide blocky shapes and photographic textures.",
    accent: "#8ebf96",
    hue: 130,
    prompt: "Image 1 is the photograph to transform. Image 2 is a visual rendering reference only. Rebuild the people, animals, and location from image 1 using the precise old-game rendering aesthetic visible in image 2: large blocky segmented limbs and torsos, simple chunky heads, realistic human proportions, blurry photographic faces and clothing textures, smooth shading across broad surfaces, and detailed low-resolution scenery. Match the relationship between coarse geometry and soft photographic texture in image 2. Preserve the recognizable appearances, ages, expressions, clothing colors, poses, subject count, and composition from image 1. Keep the original photographed activity peaceful. Use image 2 only to guide rendering technique; do not copy its people, outfits, props, setting, or text. Do not add text, interfaces, borders, logos, or watermarks.",
    referenceImage: "disc-2",
  },
  {
    id: "cartridge-world",
    version: 1,
    name: "Cartridge World",
    description: "Chunky characters, soft textures, and bright early-3D platformer scenery.",
    accent: "#72d3a4",
    hue: 152,
    prompt: `Reconstruct the entire supplied photograph as a cheerful late-1990s three-dimensional console platformer scene. Build subjects and scenery from simple chunky low-polygon models with broad geometric forms, rounded-looking but visibly angular silhouettes, oversized simple hands and feet, small softly filtered low-resolution textures, basic vertex-color shading, saturated colors, and bright simple lighting. Keep photographed faces recognizable through simplified features, hair, and clothing. Give buildings and objects the same playful coarse geometry and keep the original scene layout. ${preservationPrompt}`,
  },
  {
    id: "age-of-legends",
    version: 2,
    name: "Age of Legends",
    description: "One fantasy world, many moods: woodland courts, dragon dynasties, and royal castles.",
    accent: "#cba564",
    hue: 38,
    prompt: `Reimagine the supplied photograph as a peaceful everyday moment in an original high-fantasy world, with the tangible realism of a live-action film set. Choose one coherent mood for this rendering: an elven woodland court with flowing sage fabrics, silver botanical ornaments, fine braids, and pale carved stone; a royal castle with embroidered velvet, elegant circlets, richly furnished halls, and candlelight; a dragon-themed palace with black-and-crimson tailoring, silver hair accents, elaborate braids, and dark stone; or a northern great hall with layered wool, worn leather, tied-back hair, timber, and cool daylight. Let the photo inspire the choice, and use that one mood throughout the people and surroundings. Repeated renderings may choose different moods. Use detailed practical costumes, natural materials, and original decorative designs. ${fantasyPreservationPrompt}`,
  },
  {
    id: "elven-dawn",
    version: 1,
    name: "Elven Dawn",
    description: "Silver clasps, flowing fabrics, and luminous woodland craftsmanship.",
    accent: "#add3b0",
    hue: 126,
    prompt: `Reimagine the supplied photograph as a peaceful live-action scene in an original luminous woodland fantasy civilization at dawn. Dress people in flowing layered fabrics, fine botanical embroidery, elegant travel cloaks, and delicate original silver clasps. Adapt hair with fine natural braids or graceful arrangements while retaining each person's recognizable face. Reinterpret existing structures and objects with carved wood, pale stone, leaf-inspired craftsmanship, and organic architectural forms; render existing greenery as ancient mossy woodland. Use soft pearlescent morning light, restrained silver and sage colors, and a sense of quiet wonder. Keep costume, people, and materials convincing and tangible. ${fantasyPreservationPrompt}`,
  },
  {
    id: "frost-and-crown",
    version: 1,
    name: "Frost & Crown",
    description: "Weathered castles, dark wool, braided hair, and cold cinematic daylight.",
    accent: "#98b2ce",
    hue: 212,
    prompt: `Reimagine the supplied photograph as a grounded live-action medieval fantasy court or northern town during a calm everyday moment. Dress people in heavy woven wool, layered linen, weathered dark leather, modest embroidered cloaks, and distinctive original metal clasps. Adapt hair into practical braids, tied-back styles, or courtly updos where appropriate. Reinterpret existing buildings and objects as weathered stone halls, timber furnishings, old courtyards, and handcrafted medieval equivalents. Use cold natural daylight, subtle warm candlelight in interiors, slate blue and earthy brown colors, and richly detailed practical costumes. ${fantasyPreservationPrompt}`,
  },
  {
    id: "paper-universe",
    version: 1,
    name: "Paper Universe",
    description: "Folded paper, layered silhouettes, and tiny sculpted shadows.",
    accent: "#dfb996",
    hue: 29,
    prompt: `Rebuild the entire supplied photograph as an intricate handcrafted layered-paper diorama. Construct people, animals, objects, and scenery from carefully cut colored paper, folded planes, curled paper details, and stacked silhouettes with visible paper fibers and tiny cast shadows. Use thoughtfully simplified facial shapes that retain the subjects' recognizable features. Give the whole scene convincing miniature depth, soft studio lighting, and a coordinated warm paper palette. ${preservationPrompt}`,
  },
  {
    id: "soft-spot",
    version: 1,
    name: "Soft Spot",
    description: "Padded felt figures, woolly scenery, and embroidered details.",
    accent: "#e4a4be",
    hue: 336,
    prompt: `Rebuild the entire supplied photograph as an unmistakably handmade scene of stuffed felt puppets and textile scenery. Make each face from clearly visible pieces of fuzzy colored felt with sewn edges, padded cheeks, a simple fabric nose, and embroidered eyes, brows, and mouth. Make hair or fur from wool yarn and clothing from stitched miniature fabric pieces. Retain the subjects' recognizable face shapes, hair, coloring, and characteristic clothing through this simplified puppet design. Construct every object and background surface from layered felt, knitted wool, or cloth, with visible seams, fibers, and handcrafted joins. Use soft warm studio light and convincing miniature depth. ${preservationPrompt}`,
  },
  {
    id: "neon-rain",
    version: 1,
    name: "Neon Rain",
    description: "Neon reflections, cinematic color, and a quietly futuristic night.",
    accent: "#b29bff",
    hue: 254,
    prompt: `Restyle the supplied photograph as a cinematic near-future city night scene with luminous cyan, violet, and warm coral accent lighting. Reinterpret existing surroundings with subtle practical futuristic materials and abstract unlettered light panels. In exterior areas, add lightly rain-wet surfaces and reflected colored light; in interiors, keep the room dry and place any rain beyond existing windows. Keep faces naturally readable and clothing intact. Use atmospheric depth, gentle haze, rich shadows, and convincing photographic detail while keeping the scene calm and the subjects relaxed. ${preservationPrompt}`,
  },
  {
    id: "riso-club",
    version: 1,
    name: "Riso Club",
    description: "Three-color printmaking with grain and charmingly imperfect registration.",
    accent: "#f08a8e",
    hue: 358,
    prompt: `Redraw the entire supplied photograph as a beautifully crafted three-ink risograph art print on warm ivory paper. Use a limited palette of coral, teal, and deep indigo, with translucent overprinted colors, bold simplified shapes, textured halftones, visible paper grain, and small natural registration offsets. Preserve recognizable faces, poses, and important objects through expressive economical linework and carefully chosen color shapes. Fill the whole image with the artwork. ${preservationPrompt}`,
  },
  {
    id: "stained-in-light",
    version: 1,
    name: "Stained in Light",
    description: "Luminous jewel-colored glass and carefully traced dark outlines.",
    accent: "#78bed8",
    hue: 196,
    prompt: `Reconstruct the entire supplied photograph as an intricate luminous stained-glass artwork. Divide the subjects, objects, and surroundings into thoughtfully shaped translucent glass pieces joined by slender dark lead lines. Use jewel colors, subtle rippled glass textures, and warm light glowing through the composition. Design the facial pieces carefully so photographed people remain recognizable and expressive. Apply the glass construction throughout the image and fill the frame with the artwork itself. ${preservationPrompt}`,
  },
  {
    id: "blueprint-universe",
    version: 1,
    name: "Blueprint Universe",
    description: "Fine white contours and dimensional technical drawing on deep cyan.",
    accent: "#74b9ed",
    hue: 205,
    prompt: `Redraw the entire supplied photograph as an elegant cyanotype-inspired technical illustration on deep cyan-blue paper. Describe every person, animal, object, and background structure with fine white contour lines, delicate internal construction lines, restrained cross-hatching, and a few translucent pale-blue planes for depth. Keep faces recognizable through carefully drawn facial contours and characteristic hair and clothing details. Maintain the photographed perspective and composition. Use purely visual linework without labels, letters, numbers, measurements, or annotations. ${preservationPrompt}`,
  },
]);

// Retired styles remain resolvable for existing photos, shared links, and queued jobs.
// Only the active catalog is advertised in the capture and restyle pickers.
const retiredIds = new Set([
  "disc-2-smooth",
  "disc-2-wide",
  "disc-2-smooth-wide",
  "disc-2-1996",
  "disc-2-reference",
  "once-upon-a-cel",
  "cartridge-world",
  "elven-dawn",
  "frost-and-crown",
  "riso-club",
  "blueprint-universe",
]);

export const presets = presetCatalog.filter((preset) => !retiredIds.has(preset.id));
export const retiredPresets = presetCatalog.filter((preset) => retiredIds.has(preset.id));

export function getPreset(id: string): Preset | undefined {
  return presetCatalog.find((preset) => preset.id === id);
}
