import { z } from "zod";

const presetSchema = z.object({
  id: z.string().regex(/^[a-z0-9-]+$/),
  version: z.number().int().positive(),
  name: z.string().min(1),
  description: z.string().min(1),
  accent: z.string().regex(/^#[0-9a-fA-F]{6}$/),
  hue: z.number().min(0).max(360),
  prompt: z.string().min(24),
});

export type Preset = z.infer<typeof presetSchema>;

const preservationPrompt =
  "Preserve the main subject, recognizable identity, pose, composition, camera angle, and important scene geometry. Apply the requested aesthetic consistently across the image. Do not add captions, logos, borders, signatures, or watermarks.";

const fantasyPreservationPrompt =
  "Preserve each person's recognizable facial identity, age, expression, and pose. Replace contemporary clothing and accessories with the requested fantasy designs. Replace modern headwear with a handcrafted period-style cloth cap or hood that keeps the face visible. Adapt hairstyles to the setting while retaining each person's facial identity. Preserve the composition, camera angle, and overall layout while reinterpreting surroundings as fantasy equivalents. Keep people comfortably clothed and the scene peaceful. Use original costumes, architecture, and heraldry. Do not add captions, logos, borders, signatures, or watermarks.";

export const presets: Preset[] = z.array(presetSchema).parse([
  {
    id: "post-apocalypse",
    version: 3,
    name: "After the End",
    description: "A quiet world reclaimed by nature: weathered buildings, greenery, and amber light.",
    accent: "#ff6c51",
    hue: 18,
    prompt: `Restyle the supplied photograph as a peaceful, long-abandoned retro-future world reclaimed by nature. Age the existing buildings, furniture, and objects with faded paint, worn surfaces, a little dust, and creeping greenery. Use warm amber sunlight, muted earth tones, and cinematic film texture. Keep the scene calm and habitable. Keep any people and animals healthy and relaxed, with their appearance and clothing intact. ${preservationPrompt}`,
  },
  {
    id: "kid-drawing",
    version: 1,
    name: "Fridge Masterpiece",
    description: "Wobbly crayons, joyful colors, and the confidence of a five-year-old artist.",
    accent: "#ffd84a",
    hue: 52,
    prompt: `Redraw the supplied photograph as an exuberant young child's crayon drawing on lightly lined off-white paper. Use wobbly outlines, uneven coloring, simplified shapes, cheerful colors, and charmingly imperfect proportions. ${preservationPrompt}`,
  },
  {
    id: "alien-visitor",
    version: 2,
    name: "First Contact",
    description: "A friendly visitor, green-violet light, and a little everyday science-fiction wonder.",
    accent: "#d7ff42",
    hue: 112,
    prompt: `Restyle the supplied photograph as a warm, playful science-fiction movie scene about meeting a friendly visitor from another planet. Add one small, friendly robot-like alien companion in an open area of the background, soft green-violet accent lighting, and a few practical retro-futuristic details. Keep the existing people and animals unchanged, healthy, relaxed, and clearly separate from the new companion; keep their clothing intact. The mood is welcoming and curious. ${preservationPrompt}`,
  },
  {
    id: "claymation",
    version: 1,
    name: "Tiny Clay World",
    description: "Hand-shaped characters, miniature sets, fingerprints, and stop-motion charm.",
    accent: "#f39b69",
    hue: 28,
    prompt: `Rebuild the supplied photograph as a handcrafted stop-motion clay animation frame. Everything should look sculpted from colorful modeling clay with tiny fingerprints, miniature practical sets, soft studio lighting, and shallow depth of field. ${preservationPrompt}`,
  },
  {
    id: "disposable-90s",
    version: 1,
    name: "Found in 1997",
    description: "Direct flash, soft focus, chunky grain, and a slightly questionable timestamp.",
    accent: "#5ac6c8",
    hue: 184,
    prompt: `Make the supplied photograph look like an authentic late-1990s consumer disposable-camera print. Use direct on-camera flash, slightly missed focus, visible film grain, modest color casts, imperfect exposure, and candid snapshot energy. Do not add a border or timestamp. ${preservationPrompt}`,
  },
  {
    id: "storybook",
    version: 1,
    name: "Bedtime Legend",
    description: "A warm, richly painted page from an old and well-loved storybook.",
    accent: "#6657de",
    hue: 248,
    prompt: `Illustrate the supplied photograph as a richly painted page from a timeless children's storybook. Use expressive gouache and watercolor textures, warm pools of light, gentle whimsy, detailed natural forms, and a sense of quiet adventure. ${preservationPrompt}`,
  },
  {
    id: "panel-one",
    version: 1,
    name: "Panel One",
    description: "Bold comic inks, halftone dots, and vintage printed color.",
    accent: "#ec765e",
    hue: 10,
    prompt: `Redraw the entire supplied photograph as a single full-bleed vintage color comic illustration. Use confident black brush outlines, expressive inked faces, simplified shadow shapes, saturated flat print colors, subtle Ben-Day halftone dots, and slightly imperfect ink registration on paper. Render all people, animals, objects, and surroundings in the same illustrated style. Keep the photographed everyday activity and give the scene lively visual energy. Use original character designs. ${preservationPrompt}`,
  },
  {
    id: "after-school",
    version: 1,
    name: "After School",
    description: "A nostalgic cel-anime frame with painted backgrounds and expressive faces.",
    accent: "#f89db7",
    hue: 342,
    prompt: `Redraw the entire supplied photograph as a nostalgic late-1990s hand-drawn cel-anime frame. Use fine confident linework, expressive eyes and brows, angular locks of hair, two-tone cel shadows, restrained highlights, richly hand-painted backgrounds, and a delicate trace of analog film grain. Translate the subjects into original anime character designs while retaining their distinctive facial features, age, expression, hairstyle, and clothing. Keep the atmosphere natural and grounded in the photographed moment. ${preservationPrompt}`,
  },
  {
    id: "prime-time",
    version: 1,
    name: "Prime Time",
    description: "Your everyday cast in a bright, flat-color animated sitcom.",
    accent: "#f2c94c",
    hue: 46,
    prompt: `Redraw the entire supplied photograph as a deliberately simple two-dimensional animated television sitcom cel. Use bold even dark outlines, large flat untextured color fills, small black-dot pupils in simple rounded eyes, chunky rounded noses, economical mouth lines, slightly ungainly comic proportions, and very minimal shadow shapes. Simplify faces into an original, gently satirical cartoon design that retains each photographed person's distinctive face shape, age, hair, and clothes. Keep all subjects and background objects equally graphic and flat, with a bright warm palette and ordinary everyday atmosphere. Use original character designs. ${preservationPrompt}`,
  },
  {
    id: "once-upon-a-cel",
    version: 1,
    name: "Once Upon a Cel",
    description: "Expressive hand-drawn characters against lush animated-film scenery.",
    accent: "#bd9be8",
    hue: 268,
    prompt: `Redraw the supplied photograph as a frame from an original hand-drawn animated fairy-tale feature film. Draw the subjects with graceful flowing contours, appealing rounded forms, expressive faces, carefully painted cel colors, and fluid-looking poses that match the photograph. Paint the surroundings with layered gouache detail, atmospheric depth, warm theatrical lighting, and a quiet sense of wonder. Use crisp character cels against richly painted scenery. Keep the original subjects recognizable and create original character designs. ${preservationPrompt}`,
  },
  {
    id: "big-screen",
    version: 1,
    name: "Big Screen",
    description: "Expressive sculpted characters and warm cinematic 3D animation.",
    accent: "#f7a85c",
    hue: 30,
    prompt: `Rebuild the entire supplied photograph as a polished frame from an original three-dimensional animated family feature. Translate people and animals into expressive sculpted characters with gently exaggerated eyes and brows, rounded but distinctive facial shapes, carefully groomed hair or fur, and tactile clothing. Give the whole scene dimensional modeled geometry, soft material shading, warm cinematic lighting, subtle depth of field, and rich color. Retain each subject's recognizable identity, age, expression, and characteristic details through the stylization. Use original character designs. ${preservationPrompt}`,
  },
  {
    id: "pocket-arcade",
    version: 1,
    name: "Pocket Arcade",
    description: "Your whole world redrawn in crisp, colorful 16-bit pixels.",
    accent: "#75bdff",
    hue: 208,
    prompt: `Rebuild the entire supplied photograph as detailed 16-bit pixel art, as though drawn on a roughly 320-pixel-wide game canvas and enlarged with crisp nearest-neighbor pixels. Construct every subject and background object from deliberate square pixel clusters with a limited coordinated palette, stepped contours, simple sprite-like shading, and selective dithering. Preserve recognizable facial, hair, and clothing cues using carefully placed pixels. Apply the pixel-art construction throughout the scene. ${preservationPrompt}`,
  },
  {
    id: "memory-card",
    version: 1,
    name: "Memory Card",
    description: "Faceted faces, boxy limbs, muddy textures: gloriously crude early 3D.",
    accent: "#a6b987",
    hue: 82,
    prompt: `Rebuild every visible surface of the supplied photograph as a visibly primitive late-1990s console 3D game render. Construct each head from only a few dozen large planar polygons, with angular ears, a wedge-like nose, crude blocky jaw, simple eye marks, rigid segmented limbs, and boxy mitten hands. Map tiny blurry 32-to-64-pixel photographic textures over these crude meshes; faces should have visibly stretched low-resolution texels and broad color patches. Represent hair as a solid angular mass and clothing as a small number of flat polygon faces. Use flat baked lighting, muted colors, dithering, and jagged low-resolution raster edges. Make the subjects as visibly crude and low-budget as the scenery. Keep the photograph's pose, viewpoint, scene layout, main colors, and distinguishing character cues recognizable at this deliberately coarse level of detail. Do not add captions, logos, borders, signatures, or watermarks.`,
  },
  {
    id: "cartridge-world",
    version: 1,
    name: "Cartridge World",
    description: "Chunky characters, soft textures, and bright early-3D platformer scenery.",
    accent: "#72d3a4",
    hue: 152,
    prompt: `Reconstruct the entire supplied photograph as a cheerful late-1990s three-dimensional console platformer scene. Build subjects and scenery from simple chunky low-polygon models with broad geometric forms, rounded-looking but visibly angular silhouettes, oversized simple hands and feet, small softly filtered low-resolution textures, basic vertex-color shading, saturated colors, and bright simple lighting. Keep photographed faces recognizable through simplified features, hair, and clothing. Give buildings and objects the same playful coarse geometry and keep the original scene layout. ${preservationPrompt}`,
  },
  {
    id: "age-of-legends",
    version: 1,
    name: "Age of Legends",
    description: "Cloaks, braided hair, and a cinematic world of forests and great halls.",
    accent: "#cba564",
    hue: 38,
    prompt: `Reimagine the supplied photograph as a grounded live-action high-fantasy film scene during a peaceful everyday moment. Dress people in richly textured layered linen, wool, worn leather, embroidered cloaks, original clasps, and subtle ceremonial metalwork. Adapt hairstyles with natural braids, tied-back lengths, or elegant updos where appropriate to the person. Reinterpret the existing surroundings as fantasy equivalents: interiors become timber-and-stone great halls or workshops, streets become old hillside towns, and greenery becomes ancient woodland. Use natural materials, warm light, gentle mist where appropriate, and detailed practical-costume realism. ${fantasyPreservationPrompt}`,
  },
  {
    id: "elven-dawn",
    version: 1,
    name: "Elven Dawn",
    description: "Silver clasps, flowing fabrics, and luminous woodland craftsmanship.",
    accent: "#add3b0",
    hue: 126,
    prompt: `Reimagine the supplied photograph as a peaceful live-action scene in an original luminous woodland fantasy civilization at dawn. Dress people in flowing layered fabrics, fine botanical embroidery, elegant travel cloaks, and delicate original silver clasps. Adapt hair with fine natural braids or graceful arrangements while retaining each person's recognizable face. Reinterpret existing structures and objects with carved wood, pale stone, leaf-inspired craftsmanship, and organic architectural forms; render existing greenery as ancient mossy woodland. Use soft pearlescent morning light, restrained silver and sage colors, and a sense of quiet wonder. Keep costume, people, and materials convincing and tangible. ${fantasyPreservationPrompt}`,
  },
  {
    id: "frost-and-crown",
    version: 1,
    name: "Frost & Crown",
    description: "Weathered castles, dark wool, braided hair, and cold cinematic daylight.",
    accent: "#98b2ce",
    hue: 212,
    prompt: `Reimagine the supplied photograph as a grounded live-action medieval fantasy court or northern town during a calm everyday moment. Dress people in heavy woven wool, layered linen, weathered dark leather, modest embroidered cloaks, and distinctive original metal clasps. Adapt hair into practical braids, tied-back styles, or courtly updos where appropriate. Reinterpret existing buildings and objects as weathered stone halls, timber furnishings, old courtyards, and handcrafted medieval equivalents. Use cold natural daylight, subtle warm candlelight in interiors, slate blue and earthy brown colors, and richly detailed practical costumes. ${fantasyPreservationPrompt}`,
  },
  {
    id: "paper-universe",
    version: 1,
    name: "Paper Universe",
    description: "Folded paper, layered silhouettes, and tiny sculpted shadows.",
    accent: "#dfb996",
    hue: 29,
    prompt: `Rebuild the entire supplied photograph as an intricate handcrafted layered-paper diorama. Construct people, animals, objects, and scenery from carefully cut colored paper, folded planes, curled paper details, and stacked silhouettes with visible paper fibers and tiny cast shadows. Use thoughtfully simplified facial shapes that retain the subjects' recognizable features. Give the whole scene convincing miniature depth, soft studio lighting, and a coordinated warm paper palette. ${preservationPrompt}`,
  },
  {
    id: "soft-spot",
    version: 1,
    name: "Soft Spot",
    description: "Padded felt figures, woolly scenery, and embroidered details.",
    accent: "#e4a4be",
    hue: 336,
    prompt: `Rebuild the entire supplied photograph as an unmistakably handmade scene of stuffed felt puppets and textile scenery. Make each face from clearly visible pieces of fuzzy colored felt with sewn edges, padded cheeks, a simple fabric nose, and embroidered eyes, brows, and mouth. Make hair or fur from wool yarn and clothing from stitched miniature fabric pieces. Retain the subjects' recognizable face shapes, hair, coloring, and characteristic clothing through this simplified puppet design. Construct every object and background surface from layered felt, knitted wool, or cloth, with visible seams, fibers, and handcrafted joins. Use soft warm studio light and convincing miniature depth. ${preservationPrompt}`,
  },
  {
    id: "neon-rain",
    version: 1,
    name: "Neon Rain",
    description: "Neon reflections, cinematic color, and a quietly futuristic night.",
    accent: "#b29bff",
    hue: 254,
    prompt: `Restyle the supplied photograph as a cinematic near-future city night scene with luminous cyan, violet, and warm coral accent lighting. Reinterpret existing surroundings with subtle practical futuristic materials and abstract unlettered light panels. In exterior areas, add lightly rain-wet surfaces and reflected colored light; in interiors, keep the room dry and place any rain beyond existing windows. Keep faces naturally readable and clothing intact. Use atmospheric depth, gentle haze, rich shadows, and convincing photographic detail while keeping the scene calm and the subjects relaxed. ${preservationPrompt}`,
  },
  {
    id: "riso-club",
    version: 1,
    name: "Riso Club",
    description: "Three-color printmaking with grain and charmingly imperfect registration.",
    accent: "#f08a8e",
    hue: 358,
    prompt: `Redraw the entire supplied photograph as a beautifully crafted three-ink risograph art print on warm ivory paper. Use a limited palette of coral, teal, and deep indigo, with translucent overprinted colors, bold simplified shapes, textured halftones, visible paper grain, and small natural registration offsets. Preserve recognizable faces, poses, and important objects through expressive economical linework and carefully chosen color shapes. Fill the whole image with the artwork. ${preservationPrompt}`,
  },
  {
    id: "stained-in-light",
    version: 1,
    name: "Stained in Light",
    description: "Luminous jewel-colored glass and carefully traced dark outlines.",
    accent: "#78bed8",
    hue: 196,
    prompt: `Reconstruct the entire supplied photograph as an intricate luminous stained-glass artwork. Divide the subjects, objects, and surroundings into thoughtfully shaped translucent glass pieces joined by slender dark lead lines. Use jewel colors, subtle rippled glass textures, and warm light glowing through the composition. Design the facial pieces carefully so photographed people remain recognizable and expressive. Apply the glass construction throughout the image and fill the frame with the artwork itself. ${preservationPrompt}`,
  },
  {
    id: "blueprint-universe",
    version: 1,
    name: "Blueprint Universe",
    description: "Fine white contours and dimensional technical drawing on deep cyan.",
    accent: "#74b9ed",
    hue: 205,
    prompt: `Redraw the entire supplied photograph as an elegant cyanotype-inspired technical illustration on deep cyan-blue paper. Describe every person, animal, object, and background structure with fine white contour lines, delicate internal construction lines, restrained cross-hatching, and a few translucent pale-blue planes for depth. Keep faces recognizable through carefully drawn facial contours and characteristic hair and clothing details. Maintain the photographed perspective and composition. Use purely visual linework without labels, letters, numbers, measurements, or annotations. ${preservationPrompt}`,
  },
]);

export function getPreset(id: string): Preset | undefined {
  return presets.find((preset) => preset.id === id);
}
